### ISSUE TITLE
API for the Data

### ISSUE THREAD

**Issue by inonoob** [ecaron/waterrower-game#1]
Hey, 

I'm the create of PiRowFlo [link](https://github.com/inonoob/pirowflo) which is a all in one data system for the Waterrower. 

Might it be possible to think about to have an API to which it is possible to send the data to. I know you already have the S4 connection done differently but might it be possible to have a standard API to which I can send the data from PiRowFlo python script to the web application ? 
PiRowFlo support next to S4 also SmartRow. And it broadcast the data over Bluetooth but also over Ant+. 

So this would be kind of an add-on for PiRowFlo running on the Pi.

**Comment by ecaron** [comment]
Interesting. @inonoob , are you suggesting that your project would have an OpenAPI spec defined and I'd adjust this to consume it? Or are you saying that you'd like me to write an API spec and you'd adjust your project to send HTTP requests to this (making this become an API server)?

**Comment by ecaron** [comment]
Didn't get a response - closing
